blank_issues_enabled: false
contact_links:
  - name: Readme
    url: https://github.com/catbee-technologies/ng-catbee#readme
    about: Check the README for more information about the project.
  - name: Documentation
    url: https://catbee.in/docs/@ng-catbee/
    about: Find in-depth information about using ng-catbee in the docs.
  - name: Discussions
    url: https://github.com/catbee-technologies/ng-catbee/discussions
    about: Ask questions or start a discussion here.
  - name: Security Policy
    url: https://github.com/catbee-technologies/ng-catbee/security/policy
    about: Report security vulnerabilities responsibly here.
